version: '3'

networks:
  default:
    external:
      name: ai_service_proxy # you need to create a overlay network named ai_service_proxy with "--attachable" manually or use cortex to deploy first


services:
  consul-node1:
    image: bitnami/consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - default 
    hostname: consulserver
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - 'consul-node1_data:/bitnami'

  consul-node2:
    image: bitnami/consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - default 
    volumes:
      - 'consul-node2_data:/bitnami'

  consul-node3:
    image: bitnami/consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - default 
    volumes:
      - 'consul-node3_data:/bitnami'
          
  registrator:
    image: gliderlabs/registrator:multinetwork  # you need to build this image from https://github.com/bindog/registrator
    networks:
      - default 
    hostname: registrator
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  
    command: -internal -explicit consul://consulserver:8500
    deploy:
      mode: global # golbal模式会在每一个节点上都只创建一个service.

  loadbalancer_nginx:
    image: load_balancing/nginx
    environment:
      - CONSUL_SERVER_HOST=consulserver
    networks:
      - default 
    hostname: lbn
    ports:
      - "8900:8900"
    depends_on:
      - registrator
  
  loadbalancer_tengine:
    image: load_balancing/tengine
    environment:
      - CONSUL_SERVER_HOST=consulserver
    networks:
      - default 
    hostname: lbt
    ports:
      - "9900:9900"
      - "9901:9901"
    depends_on:
      - registrator

volumes:
  consul-node1_data:
    driver: local
  consul-node2_data:
    driver: local
  consul-node3_data:
    driver: local
