apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-services
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /seg
        pathType: Prefix
        backend:
          service:
            name: seg-service
            port:
              number: 9999
